/**
 * Generate worldCities.ts from world-cities-json package.
 * Run with: node scripts/generate-cities.mjs
 */
import { createRequire } from 'module';
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const require = createRequire(import.meta.url);
const { cities } = require('world-cities-json');

const __dirname = dirname(fileURLToPath(import.meta.url));

// These are the country codes from countryBounds.ts
const countryCodes = new Set([
    'JP', 'IT', 'TR', 'FR', 'ES', 'DE', 'GB', 'GR', 'TH', 'IN', 'BR', 'AU', 'US', 'CA', 'MX',
    'AR', 'EG', 'ZA', 'MA', 'CN', 'KR', 'ID', 'VN', 'PT', 'NL', 'SE', 'NO', 'PE', 'CO', 'NZ',
    'KE', 'TZ', 'IS', 'HR', 'CZ', 'PL', 'AT', 'CH', 'IE', 'PH', 'MY', 'SG', 'AE', 'JO', 'IL',
    'CU', 'CR', 'CL', 'RU', 'FI', 'DK', 'BE', 'RO', 'HU', 'BG', 'LK', 'NP', 'KH', 'MM', 'LA',
    'TW', 'MN', 'PK', 'BD', 'ET', 'NG', 'GH', 'SN', 'MG', 'NA', 'BW', 'ZW', 'ZM', 'UG', 'RW',
    'PA', 'EC', 'BO', 'PY', 'UY', 'VE', 'DO', 'JM', 'GT', 'HN', 'NI', 'SA', 'OM', 'QA', 'KW',
    'LB', 'GE', 'AM', 'AZ', 'KZ', 'UZ', 'FJ', 'PG', 'DZ', 'TN', 'LY', 'IR', 'IQ', 'SY',
]);

// Build a map of countryCode -> cities
const countryMap = {};

for (const city of cities) {
    if (!countryCodes.has(city.iso2)) continue;
    if (!countryMap[city.country]) {
        countryMap[city.country] = [];
    }
    countryMap[city.country].push({
        name: city.city,
        lat: parseFloat(city.lat),
        lng: parseFloat(city.lng),
    });
}

// Sort cities alphabetically within each country
for (const country of Object.keys(countryMap)) {
    countryMap[country].sort((a, b) => a.name.localeCompare(b.name));
}

// Generate TypeScript
let output = `// Auto-generated by scripts/generate-cities.mjs — do not edit manually
// Source: world-cities-json (SimpleMaps World Cities Database)

export interface CityData {
    name: string;
    lat: number;
    lng: number;
}

export const worldCities: Record<string, CityData[]> = `;

output += JSON.stringify(countryMap, null, 2) + ';\n';

const outPath = resolve(__dirname, '..', 'src', 'data', 'worldCities.ts');
writeFileSync(outPath, output, 'utf-8');

// Print stats
const totalCities = Object.values(countryMap).reduce((sum, arr) => sum + arr.length, 0);
console.log(`✅ Generated ${outPath}`);
console.log(`   ${Object.keys(countryMap).length} countries, ${totalCities} cities`);
